### ISSUE TITLE
Arquivos .h

### ISSUE THREAD

**Issue by fspacheco** [gab5987/Jogo-C#2]
Arquivos .h são para definição de estruturas e protótipo (assinatura) de funções. São incluídos com #include. A implementação deve ser em arquivos .c, que não são incluídos com #include

**Comment by gab5987** [comment]
> Arquivos .h são para definição de estruturas e protótipo (assinatura) de funções. São incluídos com #include. A implementação deve ser em arquivos .c, que não são incluídos com #include

Corrigido! Obrigado professor
