### ISSUE TITLE
makefile

### ISSUE THREAD

**Issue by gab5987** [gab5987/Jogo-C#3]
Fazer um makefile pq digitar uma porrada de flags toda vez que for compilar é mt ruim!!!

**Comment by lusqua** [comment]
xênio

**Comment by lusqua** [comment]
Arquivo `run.sh` adiocionado para este propósito

Roda o GCC e em seguida roda o código sem maiores problemas.

TUTORIAL DE USO NA PÁGINA INICIAL DO CÓDIGO
